# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


target 'Bloc Spot' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bloc Spot
  pod 'Alamofire', '~> 3.4'

  target 'Bloc SpotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
